# Generated by Django 3.2.16 on 2022-12-16 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20210512_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quesmodel',
            name='op3',
        ),
        migrations.RemoveField(
            model_name='quesmodel',
            name='op4',
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='ans',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op1',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='quesmodel',
            name='op2',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
